# Generated by Django 4.2.11 on 2024-04-18 16:15

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_setup_roles_and_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('can_create_accounts', models.BooleanField(default=True)),
                ('can_assign_roles', models.BooleanField(default=True)),
                ('can_edit_files', models.BooleanField(default=True)),
                ('can_view_dashboard', models.BooleanField(default=True)),
                ('can_import_files', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Admin User',
                'verbose_name_plural': 'Admin Users',
                'permissions': [('can_manage_all', 'Can manage everything')],
            },
            bases=('main.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ConsultantUser',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('can_view_dashboard', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Consultant User',
                'verbose_name_plural': 'Consultant Users',
                'permissions': [('can_view_dashboard', 'Can view dashboard')],
            },
            bases=('main.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='GestionnaireUser',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('can_edit_files', models.BooleanField(default=True)),
                ('can_view_dashboard', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Gestionnaire User',
                'verbose_name_plural': 'Gestionnaire Users',
                'permissions': [('can_edit_files', 'Can edit files'), ('can_view_dashboard', 'Can view dashboard')],
            },
            bases=('main.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
